# Generated by Django 2.2.10 on 2021-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('population', models.IntegerField(default=0)),
                ('menPopulation', models.IntegerField(default=0)),
                ('womanPopulation', models.IntegerField(default=0)),
            ],
        ),
    ]
